### ISSUE TITLE
Multiple Scrobbles

### ISSUE THREAD

**Issue by Celticsgreen** [PKBeam/AMWin-RP#138] opened 2024-10-06 01:06 UTC
I am having an issue where I am getting 3-4 scrobbles per listen. Please fix this. This is extremely annoying to go back on last.fm and delete the repeats.

**Comment by PKBeam** [comment] 2024-10-06 04:15
Please follow the template for creating issues

**Comment by PKBeam** [comment] 2024-10-06 04:32
Duplicate of https://github.com/PKBeam/AMWin-RP/issues/52

**Closed by PKBeam** 2024-10-06 04:32 UTC
Labels: duplicate, no logs attached
