### ISSUE TITLE
Scrobbling stops after a few songs

### ISSUE THREAD

**Issue by TheAndromedaCat** [PKBeam/AMWin-RP#111] opened 2024-06-24 00:36 UTC
**Version Info**
Apple Music 1.4.6.85 (US)
AMWin-RP 1.4.5

**Describe the bug**
Rich presence and scrobbling stops after a few songs and won't continue until I relaunch both Apple Music and AMWin

**Log Files**
Wasn't able to get a log for it

**Comment by cowboycarters** [comment] 2024-06-30 17:39
this happens every time i check the last fm website

**Comment by Zriley56** [comment] 2024-07-16 02:07
Just wanted to mention I have this issue as well. I haven't been able to isolate what exactly causes it but at certain intervals the app will stop scrobbling until I completely relaunch apple music.

**Comment by CameronB7** [comment] 2024-07-29 11:09
Don't know if this helps but I just noticed that it stops working whenever you right click something in Apple Music, it just sometimes starts again and sometimes doesn't until you restart the app

**Comment by coleshaler** [comment] 2024-08-02 03:48
For me, if I pause the Apple Music app, scrobbling stops. have to reset Apple Music and AMWIN-RP everytime I pause

**Comment by CameronB7** [comment] 2024-08-23 14:27
For those of you who are still having issues with this, turns out you don't have to restart Apple Music. Just opening the mini player got it working again for me.

**Comment by mezojm10** [comment] 2024-09-23 17:57
Also facing this issue but can't pin down the cause

**Comment by PKBeam** [comment] 2024-10-06 04:33
Duplicate of https://github.com/PKBeam/AMWin-RP/issues/46

**Closed by PKBeam** 2024-10-06 04:33 UTC
Labels: no logs attached
