### ISSUE TITLE
App stops scrobbling after unknown time.

### ISSUE THREAD

**Issue by bengrieve** [PKBeam/AMWin-RP#107] opened 2024-05-15 20:32 UTC
Apple Music 1.4.6.85 / AMWin-RP 1.4.5
Apple Music region CA

AMWin-RP stops scrobbling after an unknown time. It doesn't communicate with last.fm at all.
I thought the issue might have been v1.4.4, but it's still happening with the latest version.

The only fix seems to be a reboot of the system.

**Comment by iammarxg** [comment] 2024-05-16 12:07
Same. Even the rich presence is broken

**Comment by pwjmi** [comment] 2024-05-21 17:19
Having the same issue, i looked at the log and the last message says "Apple Music song panel is not initialised or missing". I'm using the latest release of this project but also experienced it on an older version.

**Comment by Slingshot123** [comment] 2024-05-30 13:44
Same for me. after 2-3 songs it stops scrobbling. Saddly its unusable at the moment.

**Comment by gregraygun** [comment] 2024-05-30 15:00
I just wanted to document it is 100% usable for me currently, 8 hours a day, Mon thru Fri no issues.  TY

Running 
AM 1.4.6.85
Windows 11 Pro Version 23H2
AMWin-RP v 1.4.5

**Comment by maksymilianmichta** [comment] 2024-05-30 15:02
here are some logs each one ended in this bug , what works for me to make it work again is : ending amw process tree and next restarting apple music and then turning on amw again
im on v. 1.4.5
[2024-05-28.log](https://github.com/PKBeam/AMWin-RP/files/15501782/2024-05-28.log)
[2024-05-29.log](https://github.com/PKBeam/AMWin-RP/files/15501783/2024-05-29.log)
[2024-05-30.log](https://github.com/PKBeam/AMWin-RP/files/15501784/2024-05-30.log)
[2024-05-24.log](https://github.com/PKBeam/AMWin-RP/files/15501785/2024-05-24.log)
[2024-05-25.log](https://github.com/PKBeam/AMWin-RP/files/15501786/2024-05-25.log)

**Comment by ToniShoemaker** [comment] 2024-05-31 13:53
> here are some logs each one ended in this bug , what works for me to make it work again is : ending amw process tree and next restarting apple music and then turning on amw again im on v. 1.4.5 [2024-05-28.log](https://github.com/PKBeam/AMWin-RP/files/15501782/2024-05-28.log) [2024-05-29.log](https://github.com/PKBeam/AMWin-RP/files/15501783/2024-05-29.log) [2024-05-30.log](https://github.com/PKBeam/AMWin-RP/files/15501784/2024-05-30.log) [2024-05-24.log](https://github.com/PKBeam/AMWin-RP/files/15501785/2024-05-24.log) [2024-05-25.log](https://github.com/PKBeam/AMWin-RP/files/15501786/2024-05-25.log)

I'm experiencing the same bug at seemingly random times. Sometimes it works for hours and then I get the exact same error message in my logs. "Apple Music song panel is not initialised or missing"

**Comment by pwjmi** [comment] 2024-05-31 21:01
im fixing it by switching to the mini player and occasionally using the queue list view inside of that, i dont want to have to be doing that multiple times an hour, but its better than having to restart both apple music and amw everytime the scrobbler stops working

**Comment by ToniShoemaker** [comment] 2024-06-01 14:08
that sadly doesn‘t work for me.

**Comment by gregraygun** [comment] 2024-06-05 16:42
> I just wanted to document it is 100% usable for me currently, 8 hours a day, Mon thru Fri no issues. TY
> 
> Running AM 1.4.6.85 Windows 11 Pro Version 23H2 AMWin-RP v 1.4.5

I'm seeing this issue, If I pause music, reading of what ever is linked is broken when I click play trying to resume. 

 I then killed the Music App, and reopen, leaving AMWin-RP as it is, and then begin play, and I'm scrobbling again.  

No version changes from previous.
[2024-06-05.log](https://github.com/user-attachments/files/15593824/2024-06-05.log)

**Comment by hoodmonalisa** [comment] 2024-06-05 22:39
The same thing is still happening here.

**Comment by Otus9051** [comment] 2024-08-05 15:59
After a bit of fucking around and finding out, here are the triggers:
- Skipping songs
- Pause/Resume
- AM in the background

Weirdest thing is that it didn't happen to me before but it is now. I run Windows 10 IoT LTSC under VMware Workstation. When I had my first VM with the same setup, it was fine, but the second VM somehow has issues. Weird as hell.

Anyways as others suggested, kill AM, and open it again, works fine. I'd suggest just don't skip your music.

**Comment by iammarxg** [comment] 2024-08-05 16:04
I forgot to mention a simple fix I found a few weeks ago. Simply run AMWin-RP in administrator mode.

You don't even have to close it to refresh it every few days. I've had the current session on for more than a week at this point.

**Comment by Otus9051** [comment] 2024-08-05 17:37
@iammarxg Thanks for the advice, it works great now!
@bengrieve should now close the issue as solved to declutter the repo.

**Comment by bengrieve** [comment] 2024-08-05 23:02
That might be a solution, but it's still just a workaround.

**Comment by inzsome** [comment] 2024-08-13 08:52
> I forgot to mention a simple fix I found a few weeks ago. Simply run AMWin-RP in administrator mode.
> 
> You don't even have to close it to refresh it every few days. I've had the current session on for more than a week at this point.

@iammarxg thanks for your suggestion.
Unfortunately, this doesn't seem to fix the issue for me.

[2024-08-13.log](https://github.com/user-attachments/files/16596859/2024-08-13.log)

**Comment by iammarxg** [comment] 2024-08-13 10:01
@inzsome Please share your AMWin-RP settings (while blurring personal information. but also note if the box is filled with information or not). You're supposed to fill all 4 input boxes for LastFM. Also try clicking on Save Credentials.

**Comment by inzsome** [comment] 2024-08-13 10:21
@iammarxg Scrobbling in general works for me, it just stops after a while like for everyone else.

Since I don't really care for the Discord Rich Presence, I don't have it enabled.
Here's a screnshot of my configuration:

![image](https://github.com/user-attachments/assets/1fc7abbd-0d75-49ab-88bb-89af79953d9c)

**Comment by iammarxg** [comment] 2024-08-13 10:35
Oh well that's pretty weird then. It only stops after a while for me if I don't open it in administrator mode.

**Comment by PKBeam** [comment] 2024-10-06 04:34
Duplicate of https://github.com/PKBeam/AMWin-RP/issues/46

Please move discussion there

**Closed by PKBeam** 2024-10-06 04:34 UTC
