### ISSUE TITLE
Interacting with certain UI elements of Apple Music causes the scraper to break

### ISSUE THREAD

**Issue by 21mtd** [PKBeam/AMWin-RP#105] opened 2024-05-09 14:21 UTC
**Version Info**
AMWin-RP v1.4.5 (region: VN)
Apple Music 1.4.6.85 (1.1030.21762.0)

**Describe the bug**

Open a song context menu (right click or click `...` of a song in a playlist)
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/bc572d7e-bbc5-43bb-b8c6-3a16f1e97923)
or `...` of the current song info
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/937099d8-9682-4589-9557-b523a7fe5592)

 `Apple Music song panel is not initialised or missing` bug appears in log, which also kills the RP. 

- If you close it fast, the bug goes away by itself, RP resumed.
- If you choose Add to playlist then pick a playlist, the bug persists until you restart Apple Music app.

This happens in previous AMWin versions too I think.

**Log Files**
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/a800f5e9-d247-4fc8-b758-48deb7b6203d)

**Comment by jwl-7** [comment] 2024-05-17 09:21
This issue occurs after opening any context menu in Apple Music. The problem is Windows Automation UI will no longer find the "bridge" child window with the classname `Microsoft.UI.Content.DesktopChildSiteBridge`. I used `inspect.exe` to check out the windows for any changes, and the tree structure does not appear to change at all. 

System Info:
- Windows 11 23H2
- Apple Music 1.1030.21762.0

**Comment by PierreSchwang** [comment] 2024-06-04 15:38
I'm currently having similar issues and can reproduce that. Interestingly, using EnumChildWindows from the win32 API, I can at least find the window (though it takes tremendously longer). But I can't work with that window handle either. I'm using https://github.com/mmarquee/ui-automation and convert the HWND from JNA back into a Wrapper from the library but can't access any descendants whatsoever.

Using "Accessibility Insights for Windows" by Microsoft all Elements including their properties can still be accessed - so I guess it would be interesting to know **how** they resolve all elements and children. It is Open Source, but I'm not that fit in C# / .NET and have no idea where to look remotely: https://github.com/microsoft/accessibility-insights-windows

**Comment by PKBeam** [comment] 2024-10-07 01:17
This should be fixed in the next release.

**Comment by PKBeam** [comment] 2024-10-07 01:41
Fixed in [1.4.9](https://github.com/PKBeam/AMWin-RP/releases/tag/v1.4.9).

Feel free to reopen if you still have this issue.

**Closed by PKBeam** 2024-10-07 01:41 UTC
Labels: bug
