### ISSUE TITLE
Disappearing AMWin

### ISSUE THREAD

**Issue by IoannesBlythe** [PKBeam/AMWin-RP#69] opened 2023-12-16 05:48 UTC
**Version Info**
v1.2.6.2

**Describe the bug**
AMWin just disappears randomly. May it be after playing a song, or while the song is playing

**Log Files**
No log files. It doesn't notify me if it crashes or not. It just disappears.

**Comment by PKBeam** [comment] 2023-12-16 06:19
probably a duplicate of #66, will be fixed with next release

**Closed by PKBeam** 2023-12-16 06:19 UTC
