### ISSUE TITLE
Add search for current playing song button on Apple Music

### ISSUE THREAD

**Issue by GlxryX** [PKBeam/AMWin-RP#72] opened 2023-12-28 19:02 UTC
Add a button allowing for searching on Apple Music and Spotify
<img width="299" alt="Screenshot 2023-12-28 at 1 54 24 PM" src="https://github.com/PKBeam/AMWin-RP/assets/77895395/d4d6a22f-883e-4774-8457-d9cbbb9998f0">

**Comment by PKBeam** [comment] 2024-01-01 12:07
Duplicate of #38

**Closed by PKBeam** 2024-01-01 12:07 UTC
