### ISSUE TITLE
Apple Music not responding sometimes; add support for 1 letter song name

### ISSUE THREAD

**Issue by 21mtd** [PKBeam/AMWin-RP#89] opened 2024-03-13 09:27 UTC
**Version Info**
Apple Music: 1.4.4.41 (1.1028.10497.0)
AMWin-RP version 1.4.0 

**Describe the bug**
Apple Music (AM) not responding sometimes with high CPU usage while music still playing in background. I usually have MiniPlayer turn on with AM minimized. I'm not sure if this bug is related to MiniPlayer.

**Log Files**
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/0a9c37fb-33cd-4a23-a8c1-e0bf5d5a3bcc)

-----------------------------------------------------------------------------------------
**Feature Request**
Add support for 1 letter songs. For example, 3 by Britney Spears
I think its limited by Discord but is it possible to use invisible characters to bypass it? ([U+E0000](https://unicode-explorer.com/c/E0000))

**Comment by Pupalei** [comment] 2024-03-29 18:58
I'm also getting Apple Music not responding, and I do think it's related to the miniplayer.  When I exit AMWin I'm able to use the miniplayer no problem and then when I re-run AMWin the problem returns.  When I don't have the miniplayer open I haven't seen the problem so far.  I'm using AMWin for both Discord and Scrobbling to last.fm.

**Comment by RobinPerson** [comment] 2024-04-06 14:25
I have the same issue. I haven't found what exactly the cause is myself as it seems to only happen with specific songs from my experience.

https://github.com/PKBeam/AMWin-RP/issues/86#issuecomment-1974736716

**Comment by rabellinonico** [comment] 2024-04-08 08:11
I have the same issue when the PC disable the screen after being AFK.

**Comment by PKBeam** [comment] 2024-04-15 13:42
both issues raised should be fixed in the next release

**Closed by PKBeam** 2024-04-15 13:42 UTC
Labels: bug
