### ISSUE TITLE
Application crashes / stops running after a while

### ISSUE THREAD

**Issue by mvyiko** [PKBeam/AMWin-RP#67] opened 2023-12-11 16:22 UTC
The application crashes after a while and is therefore not showing anything on Discord.
I'm using Win 11

**Comment by 8times9** [comment] 2023-12-12 01:29
```
[19:03:21] [RPC-TRACE] Starting another read
[19:03:21] [RPC-TRACE] Begining Read of 16384 bytes
[19:03:22] [RPC-TRACE] Read Payload: Frame
[19:03:22] [RPC-INFO] Handling Response. Cmd: SetActivity, Event: 
[19:03:22] [RPC-TRACE] Enqueued Message, but queue size is 0.
[19:03:25] -- no match
[19:03:25] Previous message repeated 3 times
[19:03:25] [RPC-TRACE] Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
[19:03:25] [RPC-TRACE] Initiated shutdown procedure
[19:03:25] [RPC-TRACE] Left main read loop for some reason. Aborting: False, Shutting Down: True
[19:03:25] [RPC-TRACE] Closing the named pipe.
[19:03:25] [RPC-TRACE] Setting the connection state to DISCONNECTED
[19:03:25] [RPC-TRACE] Left Main Loop
[19:03:25] [RPC-INFO] Thread Terminated, no longer performing RPC connection.
```

**Comment by PKBeam** [comment] 2023-12-12 01:32
Please attach the entire log, from the beginning of application start.

**Comment by PKBeam** [comment] 2023-12-16 06:19
probably a duplicate of #66, will be fixed with next release

**Closed by PKBeam** 2023-12-16 06:19 UTC

**Comment by N-E-N** [comment] 2023-12-18 20:42
Same issue here
